site_prefix: cat-3062920
forcing_file: ../data/sample-cat-3062920.csv
n_steps: 10
dt: 3600
start_time: 2013032000
end_time: 2013033123
da: 11.418749923500716
slope: 88.582729
lat: 46.82607
lon: -121.81418
h_active_layer: 0.125 # Assuming wolverine glacier value
h0_snow: 2.0  # Assuming wolverine glacier value
h0_ice: 2.0  # Assuming wolverine glacier value
h0_swe: 0.6  # Assuming wolverine glacier value
h0_iwe: 1.834  # Assuming wolverine glacier value
