site_prefix: cat-3062920
forcing_file: ../data/cat-3062924.csv
n_steps: 10
dt: 3600
start_time: 2013032000
end_time: 2013033123
da: 12.464100332996395
slope: 87.7246730614023
aspect: 227.22852367330972
lon: -121.78626801
lat: 46.80106673
elev: 1916.379708685498  # meters
h_active_layer: 0.125 # Assuming wolverine glacier value
h0_snow: 2.0  # Assuming wolverine glacier value
h0_ice: 2.0  # Assuming wolverine glacier value
h0_swe: 0.6  # Assuming wolverine glacier value
h0_iwe: 1.834  # Assuming wolverine glacier value
T_rain_snow: 0.0  # air temperature that the precip converts to snow (degree C)
